ProjectManagement/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^projects/', include('ProjectsApp.urls', namespace="ProjectsManagement")),
    url(r'^admin/', include(admin.site.urls)),
)

ProjectsApp/urls.py
from django.conf.urls import patterns, include, url
from ProjectsApp import views


urlpatterns = patterns('',
    url(r'^allprojects$', views.all_projects_view, name='allprojects'),
    url(r'^alltask$', views.all_tasks_view, name='alltask'),
    url(r'^addproject$', views.new_project_view, name='new_project_view'),
    url(r'^created$',views.new_project_form, name='new_project_form'),
    url(r'^addtask$', views.new_task_view, name='new_task_view'),
    url(r'^createdt$',views.new_task_form, name='new_task_form'),
 )

ProjectsApp/models.py
from django.db import models 

class Project(models.Model):
        name = models.CharField(max_length=100)
        begin = models.DateField()
        end = models.DateField(blank=True, null=True)
        active=models.BooleanField()
        #se dejan blank en true y null porque puede no tener fecha de fin aun. 
        #Se pueden agregar mas pero estos son los necesarios
        def __unicode__(self):
            return self.name
        #Para el ordenamiento se hace por el nombre debido a que es mas sencillo que buscar por fecha de inicio 
        #y la final no siempre esta definida
        class Meta:
            ordering = ['name']

class Task(models.Model):
	   #Las tareas van a ocupar tres campos elementales en la base de datos
        name = models.CharField(max_length=150)
        begin= models.DateField()
        end = models.DateField(blank=True, null=True)
        description = models.CharField(blank=True, null=True, max_length=400)
        active=models.BooleanField()
        project = models.ForeignKey(Project)

        #se dejan blank en true y null porque puede no tener fecha de fin aun. 
        #Se pueden agregar mas pero estos son los necesarios

        def __unicode__(self):
            return self.name

        class Meta:
            ordering = ['name']

ProjectsApp/forms.py
from django import forms
from django.utils import timezone
import datetime

class project_form(forms.Form):
    name = forms.CharField(max_length=100)
    start = forms.DateInput()
    description = forms.CharField(widget=forms.Textarea)

class task_form(forms.Form):
    name = forms.CharField(max_length=100)
    project_id=forms.CharField()
    start = forms.DateInput()
    description = forms.CharField(widget=forms.Textarea)

ProjectManagement/views.py
from django.http import HttpResponse
from ProjectsApp.models import tasks, projects

#def newProject(request):

#def projects(request):
	#array_Project = projects.objects.all()
	#return render(request, 'projects.html', {'array_Project':array_Project})


#def newTask(request):

#def completeProject(request, project_id):
	#project = get_object_or_404(projects, pk=project_id)
	#project.completed = True
	#project.save()
	#return HttpResponseRedirect(reverse('ProjectManagement:projectsInProgress'))

ProjectsApp/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from ProjectsApp.models import Task, Project
import datetime
import os


def all_projects_view(request):
	array_Project = Project.objects.all()
	return render(request, 'projects.html', {'array_Project':array_Project})

def new_project_form(request):
	return render(request,'addProject.html')

def new_project_view(request):
	p = Project(name=request.POST['name'], begin = request.POST['begin'], active=True)
	p.save()
	return HttpResponseRedirect(reverse('ProjectsManagement:new_project_form'))

def all_tasks_view(request):
	array_Project = Project.objects.all()
	array_task = Task.objects.all()
	return render(request, 'tasks.html',{'array_task':array_task})

def new_task_view(request):
	array_Project = Project.objects.all()
	t = Task(name=request.POST['name'],begin = request.POST['begin'] , description= request.POST['description'], project_id = 1, active=True)
	t.save()
	return HttpResponseRedirect(reverse('ProjectsManagement:new_task_form'))

def new_task_form(request):
	return render(request,'newTask.html')

def search_view(request):
	p= Project.objects.all()
	search = Project.objects.filter(name=request.POST['b'])
	return HttpResponseRedirect(reverse('ProjectsManagement:search_form'))

def search_form(request):
	return render(request,'projects.html')

ProjectsApp/templates/addProject.html
{% extends "base.html" %}


	{% block content %}
	<div class="span6 centro offset3">
		<form action="{% url 'ProjectsManagement:new_project_view' %}" method="POST">
		<br>
			{% csrf_token %}
			<label for="">Type your Project's Name!</label>
			<input name ="name" type="text">
			<br>
			<br>
			<label for="">When it starts?!</label>
			<input name ="begin" type="date">
			<br>
			<br>
			<section class= "offset 1">	
				<input type="submit" class="btn btn-inverse" >
			</section>	
		</form>
		<br>
		<br>
		<form action="/projects/allprojects">
			<input type="submit" class="btn btn-success" value="Back to Projects">
		</form>
	</div>
	{% endblock %}	

ProjectsApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/static/bootstrap/css/reset.css" rel="stylesheet">
    <title>PROJECTS</title>
  </head>

  <body background="/static/bg.jpg">
    <div class="container">
      <div class="row-fluid span12" >
          <div class="page-header">
            <h1 class="bonito"><strong>PROJECTS</strong></h1>
          </div>
          <nav class="navbar navbar-inverse">
              <li class="span2"><a href="{%url 'ProjectsManagement:allprojects' %}" class="brand">Active Projects</a></li>
              <li class="span2"><a href="{%url 'ProjectsManagement:new_project_form' %}" class="brand">Create Project</a></li>
              <li class="span2"><a href="{%url 'ProjectsManagement:alltask' %}" class="brand">Active Task</a></li>
              <li class="span2"><a href="{%url 'ProjectsManagement:new_task_form' %}" class="brand">New Task</a></li>

              <form class="navbar-search pull-right">
                  <input name = "b" type="text" class="search-query" placeholder="Search Projects">
                  <form action="{% url 'ProjectsManagement:allprojects' %}" method="POST">
                  {% csrf_token %}
                    <input type="submit" class="btn btn-inverse" value="Search">
                   </form>
              </form>
            <ul class="nav">
              {% block nav %}{% endblock %}
            </ul>
          </nav> 
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>
    </div>
  <script src="/static/bootstrap/js/bootstrap.js"></script>
  </body>
</html>

ProjectsApp/templates/newTask.html
{% extends "base.html" %}

{% block content %}
<div class="span6 centro offset3">
	<form action="{% url 'ProjectsManagement:new_task_view' %}" method="POST">
		<br>
			{% csrf_token %}
						<label for="">Type your Task's Name!</label>
						<input name ="name" type="text">
						<br>
						<br>
						<label for="">When it starts?!</label>
						<input name ="begin" type="date">
						<br>
						<br>
						<label for="">Tell me something about it</label>
						<input name ="description" type="textfield">
						<br>
						<br>
						<label for="">it belong to any project?</label>
						<select name="Projects">
							{% for p in array_Project %}
   							<option>{{p.name}}</option>
   							{% endfor %}
						</select>
					<section class= "offset 1">	
						<input type="submit" class="btn btn-inverse" >
					</section>	
	</form>
		<br>
		<br>
	<form action="/projects/tasks">
		<input type="submit" class="btn btn-success" value="Back to Tasks">
	</form>
</div>	
{% endblock %}	

ProjectsApp/templates/projects.html
{% extends "base.html" %}
   
    {% block content %}
        <div class="row-fluid span12">
            <table class="table table-bordered table-striped table-hover">
                <tr>
                <th class="span5">Name</th>
                <th class="span5">Start Date</th>
                <th class="span5">Completed</th>
                <th class="span5">Active</th>
                <th class="span5">Project's Tasks</th>
                </tr>
                {% for project in array_Project %}
                    <tr>    
                    <td class="span5"><a href="{% url 'ProjectsManagement:allprojects'%}">{{project.name}}</a></td>
                    <td class="span5">{{project.begin}}</td>
                    <td class="span5">{{project.end}}</td>
                    <td class="span5">{{project.active}}</td>  
                    <td class="span5"><a href="#">Let's see</a></td>  
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endblock %} 

ProjectsApp/templates/tasks.html
{% extends "base.html" %}

{% block content %}

<div class="row-fluid span12">
            <table class="table table-bordered table-striped table-hover">
                <tr>
                <th class="span5">Name</th>
                <th class="span5">Start Date</th>
                <th class="span5">Completed</th>
                <th class="span5">Active</th>
                <th class="span5">This is a Task of...</th>
                </tr>
                {% for t in array_task %}
                    <tr>    
                    <td class="span5"><a href="{% url 'ProjectsManagement:alltask'%}">{{t.name}}</a></td>
                    <td class="span5">{{t.begin}}</td>
                    <td class="span5">{{t.end}}</td>
                    <td class="span5">{{t.active}}</td> 
                    <td class="span5">{{t.project}}</td>  
                    </tr>
                {% endfor %}
            </table>
        </div>
 
{% endblock %}